//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8825
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;

namespace HealthManagement.Model
{

    /// <summary>
    /// 实体类IME_QC_KEY_MODULE_INFO 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Serializable]
    public class IME_QC_KEY_MODULE_INFO : Entity
    {
        public IME_QC_KEY_MODULE_INFO() : base("IME_QC_KEY_MODULE_INFO") { }

        #region Model
        private string _GID;
        private string _IME_QC_KEY_MODULE_GID;
        private string _MD_ROUTE_OPERATION_GID;
        private string _MD_ROUTE_OPERATION_CODE;
        private string _MD_ROUTE_OPERATION_NAME;
        private string _MD_MATERIEL_INFO_GID;
        private string _MD_MATERIEL_INFO_CODE;
        private string _MD_MATERIEL_INFO_NAME;
        private string _MD_MEASUREMENT_UNIT_GID;
        private string _MD_MEASUREMENT_UNIT_NAME;
        private string _BAR_CODE;
        private int? _AMOUNT;
        private int? _BUNDLING_STATUS;
        private string _CREATE_BY;
        private object _CREATE_TIME;
        private string _UPDATE_BY;
        private object _UPDATE_TIME;
        private int? _IS_DELETE;
        private int? _IS_ACTIVE;
        private string _SM_BUSI_GROUP_GID;
        private string _SM_BUSI_UNIT_GID;
        private int? _VERSION_NUM;
        private string _UDA1;
        private string _UDA2;
        private string _UDA3;
        private string _UDA4;
        private string _UDA5;
        private string _UDA6;
        private string _UDA7;
        private string _UDA8;
        private string _UDA9;
        private string _UDA10;
        private string _UDA11;
        private string _UDA12;
        private string _UDA13;
        private string _UDA14;
        private string _UDA15;
        private string _UDA16;
        private string _UDA17;
        private string _UDA18;
        private string _UDA19;
        private string _UDA20;
        /// <summary>
        /// 
        /// </summary>
        public string GID
        {
            get { return _GID; }
            set
            {
                this.OnPropertyValueChange(_.GID, _GID, value);
                this._GID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string IME_QC_KEY_MODULE_GID
        {
            get { return _IME_QC_KEY_MODULE_GID; }
            set
            {
                this.OnPropertyValueChange(_.IME_QC_KEY_MODULE_GID, _IME_QC_KEY_MODULE_GID, value);
                this._IME_QC_KEY_MODULE_GID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MD_ROUTE_OPERATION_GID
        {
            get { return _MD_ROUTE_OPERATION_GID; }
            set
            {
                this.OnPropertyValueChange(_.MD_ROUTE_OPERATION_GID, _MD_ROUTE_OPERATION_GID, value);
                this._MD_ROUTE_OPERATION_GID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MD_ROUTE_OPERATION_CODE
        {
            get { return _MD_ROUTE_OPERATION_CODE; }
            set
            {
                this.OnPropertyValueChange(_.MD_ROUTE_OPERATION_CODE, _MD_ROUTE_OPERATION_CODE, value);
                this._MD_ROUTE_OPERATION_CODE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MD_ROUTE_OPERATION_NAME
        {
            get { return _MD_ROUTE_OPERATION_NAME; }
            set
            {
                this.OnPropertyValueChange(_.MD_ROUTE_OPERATION_NAME, _MD_ROUTE_OPERATION_NAME, value);
                this._MD_ROUTE_OPERATION_NAME = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MD_MATERIEL_INFO_GID
        {
            get { return _MD_MATERIEL_INFO_GID; }
            set
            {
                this.OnPropertyValueChange(_.MD_MATERIEL_INFO_GID, _MD_MATERIEL_INFO_GID, value);
                this._MD_MATERIEL_INFO_GID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MD_MATERIEL_INFO_CODE
        {
            get { return _MD_MATERIEL_INFO_CODE; }
            set
            {
                this.OnPropertyValueChange(_.MD_MATERIEL_INFO_CODE, _MD_MATERIEL_INFO_CODE, value);
                this._MD_MATERIEL_INFO_CODE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MD_MATERIEL_INFO_NAME
        {
            get { return _MD_MATERIEL_INFO_NAME; }
            set
            {
                this.OnPropertyValueChange(_.MD_MATERIEL_INFO_NAME, _MD_MATERIEL_INFO_NAME, value);
                this._MD_MATERIEL_INFO_NAME = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MD_MEASUREMENT_UNIT_GID
        {
            get { return _MD_MEASUREMENT_UNIT_GID; }
            set
            {
                this.OnPropertyValueChange(_.MD_MEASUREMENT_UNIT_GID, _MD_MEASUREMENT_UNIT_GID, value);
                this._MD_MEASUREMENT_UNIT_GID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MD_MEASUREMENT_UNIT_NAME
        {
            get { return _MD_MEASUREMENT_UNIT_NAME; }
            set
            {
                this.OnPropertyValueChange(_.MD_MEASUREMENT_UNIT_NAME, _MD_MEASUREMENT_UNIT_NAME, value);
                this._MD_MEASUREMENT_UNIT_NAME = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string BAR_CODE
        {
            get { return _BAR_CODE; }
            set
            {
                this.OnPropertyValueChange(_.BAR_CODE, _BAR_CODE, value);
                this._BAR_CODE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? AMOUNT
        {
            get { return _AMOUNT; }
            set
            {
                this.OnPropertyValueChange(_.AMOUNT, _AMOUNT, value);
                this._AMOUNT = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? BUNDLING_STATUS
        {
            get { return _BUNDLING_STATUS; }
            set
            {
                this.OnPropertyValueChange(_.BUNDLING_STATUS, _BUNDLING_STATUS, value);
                this._BUNDLING_STATUS = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CREATE_BY
        {
            get { return _CREATE_BY; }
            set
            {
                this.OnPropertyValueChange(_.CREATE_BY, _CREATE_BY, value);
                this._CREATE_BY = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public object CREATE_TIME
        {
            get { return _CREATE_TIME; }
            set
            {
                this.OnPropertyValueChange(_.CREATE_TIME, _CREATE_TIME, value);
                this._CREATE_TIME = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UPDATE_BY
        {
            get { return _UPDATE_BY; }
            set
            {
                this.OnPropertyValueChange(_.UPDATE_BY, _UPDATE_BY, value);
                this._UPDATE_BY = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public object UPDATE_TIME
        {
            get { return _UPDATE_TIME; }
            set
            {
                this.OnPropertyValueChange(_.UPDATE_TIME, _UPDATE_TIME, value);
                this._UPDATE_TIME = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? IS_DELETE
        {
            get { return _IS_DELETE; }
            set
            {
                this.OnPropertyValueChange(_.IS_DELETE, _IS_DELETE, value);
                this._IS_DELETE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? IS_ACTIVE
        {
            get { return _IS_ACTIVE; }
            set
            {
                this.OnPropertyValueChange(_.IS_ACTIVE, _IS_ACTIVE, value);
                this._IS_ACTIVE = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SM_BUSI_GROUP_GID
        {
            get { return _SM_BUSI_GROUP_GID; }
            set
            {
                this.OnPropertyValueChange(_.SM_BUSI_GROUP_GID, _SM_BUSI_GROUP_GID, value);
                this._SM_BUSI_GROUP_GID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string SM_BUSI_UNIT_GID
        {
            get { return _SM_BUSI_UNIT_GID; }
            set
            {
                this.OnPropertyValueChange(_.SM_BUSI_UNIT_GID, _SM_BUSI_UNIT_GID, value);
                this._SM_BUSI_UNIT_GID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? VERSION_NUM
        {
            get { return _VERSION_NUM; }
            set
            {
                this.OnPropertyValueChange(_.VERSION_NUM, _VERSION_NUM, value);
                this._VERSION_NUM = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA1
        {
            get { return _UDA1; }
            set
            {
                this.OnPropertyValueChange(_.UDA1, _UDA1, value);
                this._UDA1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA2
        {
            get { return _UDA2; }
            set
            {
                this.OnPropertyValueChange(_.UDA2, _UDA2, value);
                this._UDA2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA3
        {
            get { return _UDA3; }
            set
            {
                this.OnPropertyValueChange(_.UDA3, _UDA3, value);
                this._UDA3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA4
        {
            get { return _UDA4; }
            set
            {
                this.OnPropertyValueChange(_.UDA4, _UDA4, value);
                this._UDA4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA5
        {
            get { return _UDA5; }
            set
            {
                this.OnPropertyValueChange(_.UDA5, _UDA5, value);
                this._UDA5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA6
        {
            get { return _UDA6; }
            set
            {
                this.OnPropertyValueChange(_.UDA6, _UDA6, value);
                this._UDA6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA7
        {
            get { return _UDA7; }
            set
            {
                this.OnPropertyValueChange(_.UDA7, _UDA7, value);
                this._UDA7 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA8
        {
            get { return _UDA8; }
            set
            {
                this.OnPropertyValueChange(_.UDA8, _UDA8, value);
                this._UDA8 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA9
        {
            get { return _UDA9; }
            set
            {
                this.OnPropertyValueChange(_.UDA9, _UDA9, value);
                this._UDA9 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA10
        {
            get { return _UDA10; }
            set
            {
                this.OnPropertyValueChange(_.UDA10, _UDA10, value);
                this._UDA10 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA11
        {
            get { return _UDA11; }
            set
            {
                this.OnPropertyValueChange(_.UDA11, _UDA11, value);
                this._UDA11 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA12
        {
            get { return _UDA12; }
            set
            {
                this.OnPropertyValueChange(_.UDA12, _UDA12, value);
                this._UDA12 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA13
        {
            get { return _UDA13; }
            set
            {
                this.OnPropertyValueChange(_.UDA13, _UDA13, value);
                this._UDA13 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA14
        {
            get { return _UDA14; }
            set
            {
                this.OnPropertyValueChange(_.UDA14, _UDA14, value);
                this._UDA14 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA15
        {
            get { return _UDA15; }
            set
            {
                this.OnPropertyValueChange(_.UDA15, _UDA15, value);
                this._UDA15 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA16
        {
            get { return _UDA16; }
            set
            {
                this.OnPropertyValueChange(_.UDA16, _UDA16, value);
                this._UDA16 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA17
        {
            get { return _UDA17; }
            set
            {
                this.OnPropertyValueChange(_.UDA17, _UDA17, value);
                this._UDA17 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA18
        {
            get { return _UDA18; }
            set
            {
                this.OnPropertyValueChange(_.UDA18, _UDA18, value);
                this._UDA18 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA19
        {
            get { return _UDA19; }
            set
            {
                this.OnPropertyValueChange(_.UDA19, _UDA19, value);
                this._UDA19 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UDA20
        {
            get { return _UDA20; }
            set
            {
                this.OnPropertyValueChange(_.UDA20, _UDA20, value);
                this._UDA20 = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.GID};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.GID,
                _.IME_QC_KEY_MODULE_GID,
                _.MD_ROUTE_OPERATION_GID,
                _.MD_ROUTE_OPERATION_CODE,
                _.MD_ROUTE_OPERATION_NAME,
                _.MD_MATERIEL_INFO_GID,
                _.MD_MATERIEL_INFO_CODE,
                _.MD_MATERIEL_INFO_NAME,
                _.MD_MEASUREMENT_UNIT_GID,
                _.MD_MEASUREMENT_UNIT_NAME,
                _.BAR_CODE,
                _.AMOUNT,
                _.BUNDLING_STATUS,
                _.CREATE_BY,
                _.CREATE_TIME,
                _.UPDATE_BY,
                _.UPDATE_TIME,
                _.IS_DELETE,
                _.IS_ACTIVE,
                _.SM_BUSI_GROUP_GID,
                _.SM_BUSI_UNIT_GID,
                _.VERSION_NUM,
                _.UDA1,
                _.UDA2,
                _.UDA3,
                _.UDA4,
                _.UDA5,
                _.UDA6,
                _.UDA7,
                _.UDA8,
                _.UDA9,
                _.UDA10,
                _.UDA11,
                _.UDA12,
                _.UDA13,
                _.UDA14,
                _.UDA15,
                _.UDA16,
                _.UDA17,
                _.UDA18,
                _.UDA19,
                _.UDA20};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._GID,
                this._IME_QC_KEY_MODULE_GID,
                this._MD_ROUTE_OPERATION_GID,
                this._MD_ROUTE_OPERATION_CODE,
                this._MD_ROUTE_OPERATION_NAME,
                this._MD_MATERIEL_INFO_GID,
                this._MD_MATERIEL_INFO_CODE,
                this._MD_MATERIEL_INFO_NAME,
                this._MD_MEASUREMENT_UNIT_GID,
                this._MD_MEASUREMENT_UNIT_NAME,
                this._BAR_CODE,
                this._AMOUNT,
                this._BUNDLING_STATUS,
                this._CREATE_BY,
                this._CREATE_TIME,
                this._UPDATE_BY,
                this._UPDATE_TIME,
                this._IS_DELETE,
                this._IS_ACTIVE,
                this._SM_BUSI_GROUP_GID,
                this._SM_BUSI_UNIT_GID,
                this._VERSION_NUM,
                this._UDA1,
                this._UDA2,
                this._UDA3,
                this._UDA4,
                this._UDA5,
                this._UDA6,
                this._UDA7,
                this._UDA8,
                this._UDA9,
                this._UDA10,
                this._UDA11,
                this._UDA12,
                this._UDA13,
                this._UDA14,
                this._UDA15,
                this._UDA16,
                this._UDA17,
                this._UDA18,
                this._UDA19,
                this._UDA20};
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(IDataReader reader)
        {
            this._GID = DataUtils.ConvertValue<string>(reader["GID"]);
            this._IME_QC_KEY_MODULE_GID = DataUtils.ConvertValue<string>(reader["IME_QC_KEY_MODULE_GID"]);
            this._MD_ROUTE_OPERATION_GID = DataUtils.ConvertValue<string>(reader["MD_ROUTE_OPERATION_GID"]);
            this._MD_ROUTE_OPERATION_CODE = DataUtils.ConvertValue<string>(reader["MD_ROUTE_OPERATION_CODE"]);
            this._MD_ROUTE_OPERATION_NAME = DataUtils.ConvertValue<string>(reader["MD_ROUTE_OPERATION_NAME"]);
            this._MD_MATERIEL_INFO_GID = DataUtils.ConvertValue<string>(reader["MD_MATERIEL_INFO_GID"]);
            this._MD_MATERIEL_INFO_CODE = DataUtils.ConvertValue<string>(reader["MD_MATERIEL_INFO_CODE"]);
            this._MD_MATERIEL_INFO_NAME = DataUtils.ConvertValue<string>(reader["MD_MATERIEL_INFO_NAME"]);
            this._MD_MEASUREMENT_UNIT_GID = DataUtils.ConvertValue<string>(reader["MD_MEASUREMENT_UNIT_GID"]);
            this._MD_MEASUREMENT_UNIT_NAME = DataUtils.ConvertValue<string>(reader["MD_MEASUREMENT_UNIT_NAME"]);
            this._BAR_CODE = DataUtils.ConvertValue<string>(reader["BAR_CODE"]);
            this._AMOUNT = DataUtils.ConvertValue<int?>(reader["AMOUNT"]);
            this._BUNDLING_STATUS = DataUtils.ConvertValue<int?>(reader["BUNDLING_STATUS"]);
            this._CREATE_BY = DataUtils.ConvertValue<string>(reader["CREATE_BY"]);
            this._CREATE_TIME = DataUtils.ConvertValue<object>(reader["CREATE_TIME"]);
            this._UPDATE_BY = DataUtils.ConvertValue<string>(reader["UPDATE_BY"]);
            this._UPDATE_TIME = DataUtils.ConvertValue<object>(reader["UPDATE_TIME"]);
            this._IS_DELETE = DataUtils.ConvertValue<int?>(reader["IS_DELETE"]);
            this._IS_ACTIVE = DataUtils.ConvertValue<int?>(reader["IS_ACTIVE"]);
            this._SM_BUSI_GROUP_GID = DataUtils.ConvertValue<string>(reader["SM_BUSI_GROUP_GID"]);
            this._SM_BUSI_UNIT_GID = DataUtils.ConvertValue<string>(reader["SM_BUSI_UNIT_GID"]);
            this._VERSION_NUM = DataUtils.ConvertValue<int?>(reader["VERSION_NUM"]);
            this._UDA1 = DataUtils.ConvertValue<string>(reader["UDA1"]);
            this._UDA2 = DataUtils.ConvertValue<string>(reader["UDA2"]);
            this._UDA3 = DataUtils.ConvertValue<string>(reader["UDA3"]);
            this._UDA4 = DataUtils.ConvertValue<string>(reader["UDA4"]);
            this._UDA5 = DataUtils.ConvertValue<string>(reader["UDA5"]);
            this._UDA6 = DataUtils.ConvertValue<string>(reader["UDA6"]);
            this._UDA7 = DataUtils.ConvertValue<string>(reader["UDA7"]);
            this._UDA8 = DataUtils.ConvertValue<string>(reader["UDA8"]);
            this._UDA9 = DataUtils.ConvertValue<string>(reader["UDA9"]);
            this._UDA10 = DataUtils.ConvertValue<string>(reader["UDA10"]);
            this._UDA11 = DataUtils.ConvertValue<string>(reader["UDA11"]);
            this._UDA12 = DataUtils.ConvertValue<string>(reader["UDA12"]);
            this._UDA13 = DataUtils.ConvertValue<string>(reader["UDA13"]);
            this._UDA14 = DataUtils.ConvertValue<string>(reader["UDA14"]);
            this._UDA15 = DataUtils.ConvertValue<string>(reader["UDA15"]);
            this._UDA16 = DataUtils.ConvertValue<string>(reader["UDA16"]);
            this._UDA17 = DataUtils.ConvertValue<string>(reader["UDA17"]);
            this._UDA18 = DataUtils.ConvertValue<string>(reader["UDA18"]);
            this._UDA19 = DataUtils.ConvertValue<string>(reader["UDA19"]);
            this._UDA20 = DataUtils.ConvertValue<string>(reader["UDA20"]);
        }
        /// <summary>
        /// 给当前实体赋值
        /// </summary>
        public override void SetPropertyValues(DataRow row)
        {
            this._GID = DataUtils.ConvertValue<string>(row["GID"]);
            this._IME_QC_KEY_MODULE_GID = DataUtils.ConvertValue<string>(row["IME_QC_KEY_MODULE_GID"]);
            this._MD_ROUTE_OPERATION_GID = DataUtils.ConvertValue<string>(row["MD_ROUTE_OPERATION_GID"]);
            this._MD_ROUTE_OPERATION_CODE = DataUtils.ConvertValue<string>(row["MD_ROUTE_OPERATION_CODE"]);
            this._MD_ROUTE_OPERATION_NAME = DataUtils.ConvertValue<string>(row["MD_ROUTE_OPERATION_NAME"]);
            this._MD_MATERIEL_INFO_GID = DataUtils.ConvertValue<string>(row["MD_MATERIEL_INFO_GID"]);
            this._MD_MATERIEL_INFO_CODE = DataUtils.ConvertValue<string>(row["MD_MATERIEL_INFO_CODE"]);
            this._MD_MATERIEL_INFO_NAME = DataUtils.ConvertValue<string>(row["MD_MATERIEL_INFO_NAME"]);
            this._MD_MEASUREMENT_UNIT_GID = DataUtils.ConvertValue<string>(row["MD_MEASUREMENT_UNIT_GID"]);
            this._MD_MEASUREMENT_UNIT_NAME = DataUtils.ConvertValue<string>(row["MD_MEASUREMENT_UNIT_NAME"]);
            this._BAR_CODE = DataUtils.ConvertValue<string>(row["BAR_CODE"]);
            this._AMOUNT = DataUtils.ConvertValue<int?>(row["AMOUNT"]);
            this._BUNDLING_STATUS = DataUtils.ConvertValue<int?>(row["BUNDLING_STATUS"]);
            this._CREATE_BY = DataUtils.ConvertValue<string>(row["CREATE_BY"]);
            this._CREATE_TIME = DataUtils.ConvertValue<object>(row["CREATE_TIME"]);
            this._UPDATE_BY = DataUtils.ConvertValue<string>(row["UPDATE_BY"]);
            this._UPDATE_TIME = DataUtils.ConvertValue<object>(row["UPDATE_TIME"]);
            this._IS_DELETE = DataUtils.ConvertValue<int?>(row["IS_DELETE"]);
            this._IS_ACTIVE = DataUtils.ConvertValue<int?>(row["IS_ACTIVE"]);
            this._SM_BUSI_GROUP_GID = DataUtils.ConvertValue<string>(row["SM_BUSI_GROUP_GID"]);
            this._SM_BUSI_UNIT_GID = DataUtils.ConvertValue<string>(row["SM_BUSI_UNIT_GID"]);
            this._VERSION_NUM = DataUtils.ConvertValue<int?>(row["VERSION_NUM"]);
            this._UDA1 = DataUtils.ConvertValue<string>(row["UDA1"]);
            this._UDA2 = DataUtils.ConvertValue<string>(row["UDA2"]);
            this._UDA3 = DataUtils.ConvertValue<string>(row["UDA3"]);
            this._UDA4 = DataUtils.ConvertValue<string>(row["UDA4"]);
            this._UDA5 = DataUtils.ConvertValue<string>(row["UDA5"]);
            this._UDA6 = DataUtils.ConvertValue<string>(row["UDA6"]);
            this._UDA7 = DataUtils.ConvertValue<string>(row["UDA7"]);
            this._UDA8 = DataUtils.ConvertValue<string>(row["UDA8"]);
            this._UDA9 = DataUtils.ConvertValue<string>(row["UDA9"]);
            this._UDA10 = DataUtils.ConvertValue<string>(row["UDA10"]);
            this._UDA11 = DataUtils.ConvertValue<string>(row["UDA11"]);
            this._UDA12 = DataUtils.ConvertValue<string>(row["UDA12"]);
            this._UDA13 = DataUtils.ConvertValue<string>(row["UDA13"]);
            this._UDA14 = DataUtils.ConvertValue<string>(row["UDA14"]);
            this._UDA15 = DataUtils.ConvertValue<string>(row["UDA15"]);
            this._UDA16 = DataUtils.ConvertValue<string>(row["UDA16"]);
            this._UDA17 = DataUtils.ConvertValue<string>(row["UDA17"]);
            this._UDA18 = DataUtils.ConvertValue<string>(row["UDA18"]);
            this._UDA19 = DataUtils.ConvertValue<string>(row["UDA19"]);
            this._UDA20 = DataUtils.ConvertValue<string>(row["UDA20"]);
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "IME_QC_KEY_MODULE_INFO");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field GID = new Field("GID", "IME_QC_KEY_MODULE_INFO", "GID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IME_QC_KEY_MODULE_GID = new Field("IME_QC_KEY_MODULE_GID", "IME_QC_KEY_MODULE_INFO", "IME_QC_KEY_MODULE_GID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MD_ROUTE_OPERATION_GID = new Field("MD_ROUTE_OPERATION_GID", "IME_QC_KEY_MODULE_INFO", "MD_ROUTE_OPERATION_GID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MD_ROUTE_OPERATION_CODE = new Field("MD_ROUTE_OPERATION_CODE", "IME_QC_KEY_MODULE_INFO", "MD_ROUTE_OPERATION_CODE");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MD_ROUTE_OPERATION_NAME = new Field("MD_ROUTE_OPERATION_NAME", "IME_QC_KEY_MODULE_INFO", "MD_ROUTE_OPERATION_NAME");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MD_MATERIEL_INFO_GID = new Field("MD_MATERIEL_INFO_GID", "IME_QC_KEY_MODULE_INFO", "MD_MATERIEL_INFO_GID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MD_MATERIEL_INFO_CODE = new Field("MD_MATERIEL_INFO_CODE", "IME_QC_KEY_MODULE_INFO", "MD_MATERIEL_INFO_CODE");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MD_MATERIEL_INFO_NAME = new Field("MD_MATERIEL_INFO_NAME", "IME_QC_KEY_MODULE_INFO", "MD_MATERIEL_INFO_NAME");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MD_MEASUREMENT_UNIT_GID = new Field("MD_MEASUREMENT_UNIT_GID", "IME_QC_KEY_MODULE_INFO", "MD_MEASUREMENT_UNIT_GID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MD_MEASUREMENT_UNIT_NAME = new Field("MD_MEASUREMENT_UNIT_NAME", "IME_QC_KEY_MODULE_INFO", "MD_MEASUREMENT_UNIT_NAME");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BAR_CODE = new Field("BAR_CODE", "IME_QC_KEY_MODULE_INFO", "BAR_CODE");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AMOUNT = new Field("AMOUNT", "IME_QC_KEY_MODULE_INFO", "AMOUNT");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BUNDLING_STATUS = new Field("BUNDLING_STATUS", "IME_QC_KEY_MODULE_INFO", "BUNDLING_STATUS");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CREATE_BY = new Field("CREATE_BY", "IME_QC_KEY_MODULE_INFO", "CREATE_BY");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CREATE_TIME = new Field("CREATE_TIME", "IME_QC_KEY_MODULE_INFO", "CREATE_TIME");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UPDATE_BY = new Field("UPDATE_BY", "IME_QC_KEY_MODULE_INFO", "UPDATE_BY");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UPDATE_TIME = new Field("UPDATE_TIME", "IME_QC_KEY_MODULE_INFO", "UPDATE_TIME");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IS_DELETE = new Field("IS_DELETE", "IME_QC_KEY_MODULE_INFO", "IS_DELETE");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IS_ACTIVE = new Field("IS_ACTIVE", "IME_QC_KEY_MODULE_INFO", "IS_ACTIVE");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SM_BUSI_GROUP_GID = new Field("SM_BUSI_GROUP_GID", "IME_QC_KEY_MODULE_INFO", "SM_BUSI_GROUP_GID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field SM_BUSI_UNIT_GID = new Field("SM_BUSI_UNIT_GID", "IME_QC_KEY_MODULE_INFO", "SM_BUSI_UNIT_GID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field VERSION_NUM = new Field("VERSION_NUM", "IME_QC_KEY_MODULE_INFO", "VERSION_NUM");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA1 = new Field("UDA1", "IME_QC_KEY_MODULE_INFO", "UDA1");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA2 = new Field("UDA2", "IME_QC_KEY_MODULE_INFO", "UDA2");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA3 = new Field("UDA3", "IME_QC_KEY_MODULE_INFO", "UDA3");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA4 = new Field("UDA4", "IME_QC_KEY_MODULE_INFO", "UDA4");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA5 = new Field("UDA5", "IME_QC_KEY_MODULE_INFO", "UDA5");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA6 = new Field("UDA6", "IME_QC_KEY_MODULE_INFO", "UDA6");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA7 = new Field("UDA7", "IME_QC_KEY_MODULE_INFO", "UDA7");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA8 = new Field("UDA8", "IME_QC_KEY_MODULE_INFO", "UDA8");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA9 = new Field("UDA9", "IME_QC_KEY_MODULE_INFO", "UDA9");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA10 = new Field("UDA10", "IME_QC_KEY_MODULE_INFO", "UDA10");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA11 = new Field("UDA11", "IME_QC_KEY_MODULE_INFO", "UDA11");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA12 = new Field("UDA12", "IME_QC_KEY_MODULE_INFO", "UDA12");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA13 = new Field("UDA13", "IME_QC_KEY_MODULE_INFO", "UDA13");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA14 = new Field("UDA14", "IME_QC_KEY_MODULE_INFO", "UDA14");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA15 = new Field("UDA15", "IME_QC_KEY_MODULE_INFO", "UDA15");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA16 = new Field("UDA16", "IME_QC_KEY_MODULE_INFO", "UDA16");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA17 = new Field("UDA17", "IME_QC_KEY_MODULE_INFO", "UDA17");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA18 = new Field("UDA18", "IME_QC_KEY_MODULE_INFO", "UDA18");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA19 = new Field("UDA19", "IME_QC_KEY_MODULE_INFO", "UDA19");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UDA20 = new Field("UDA20", "IME_QC_KEY_MODULE_INFO", "UDA20");
        }
        #endregion


    }
}

